### ISSUE TITLE
Error identifying, report to FerminiumASM

### ISSUE THREAD

**Issue by leonpano2006** [fonnymunkey/FermiumASM#17]
![image](https://github.com/fonnymunkey/FermiumASM/assets/58368166/4aa03eba-e008-4946-9dfd-05465e506509)
https://mclo.gs/oYGM0uX
https://mclo.gs/UqlMaZQ

**Comment by fonnymunkey** [comment]
I believe both of these crashes caused by using Cleanroom Loader.
The "Error identifying" I believe is also related to using Cleanroom Loader, but Fermium is not itself related in causing the crashes, and it is on my backlog to look into.

The first is Railcraft with a NoClassDefFoundError for sun/reflect/Reflection, I believe the latest Cleanroom is supposed to fix this automatically so try updating, but if you're already on latest then you should probably report that crash to them.

The second is also a NoClassDefFoundError for scala/collection/Seq, which the Cleanroom readme says you need to install Scalar for <https://github.com/CleanroomMC/Cleanroom/blob/main/README.md>

**Comment by leonpano2006** [comment]
These crash is fixed after installed scalar and beta version of railcraft

But error identifying is still a issue(when crash occurred for any reason)

**Comment by fonnymunkey** [comment]
Yeah the error identifying is a part of multiple conflicts between Cleanroom and Fermium that I'll move to #16 
As the conflicts are either essentially aesthetic problems like this, or only with specific config options, it is low on my priority currently compared to other projects and I will work on it eventually.
